### ISSUE TITLE
Detection doesn't react fast enough.

### ISSUE THREAD

**Issue by PrizeGotti** [Jan-Marvin/simple-auto-fishing#1]
I notice as I'm sat in the rain, with a Lure III, Luck of The Sea 3 rod, I am casting out and getting a bite, but because it's been sometimes less than a second when I get a bite, it doesn't recall the rod. I end up losing whatever that bite was have to wait for another bite for it to catch up and recall the rod.

Using 1.1.3+fabric.5867eae on 1.20.2

**Comment by Jan-Marvin** [comment]
Thank you for your feedback. 
The problem should have been fixed in the Fabric mod for the Minecraft version 1.20.4.
I rewrote the code for the Fabric version to enhance its functionality.
Now, the rod should be recalled almost instantaneously.
If you have time, please try it and provide feedback.

The Forge version is likely to have the same issue, as it contains almost identical detection code prior to the rework.
I will rewrite the Forge version version as soon as I have time.

**Comment by Jan-Marvin** [comment]
Fixed in Fabric version in f3ad628
Fixed in Forge version  in 843447d808094627444394d973e3e525cb5e3a8a
